# Generated by Django 5.0.6 on 2024-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='unique_id',
            field=models.CharField(default='placeholder_unique_id', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(),
        ),
    ]
