# Generated by Django 5.0.6 on 2024-08-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_userdata_email_alter_userdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendedarticle',
            old_name='is_clicked',
            new_name='is_liked',
        ),
        migrations.DeleteModel(
            name='ArticleInteraction',
        ),
    ]
