# Generated by Django 5.0.6 on 2024-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_userdata_is_journalist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedarticle',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='recommendedarticle',
            name='is_interacted',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
