# Generated by Django 5.0.6 on 2024-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_content_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
