# Generated by Django 5.0.6 on 2024-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_is_active_articleinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinteraction',
            name='no_of_views',
        ),
        migrations.RemoveField(
            model_name='articleinteraction',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='articleinteraction',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
