# Generated by Django 5.0.6 on 2024-08-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_articleinteraction_no_of_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
        migrations.AddField(
            model_name='news',
            name='is_real',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
        ),
    ]
